
/**
 * 
 * @author (ml) 
 * @version (11.02.2022)
 */

package blogic;

import java.lang.reflect.Constructor;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author meinhard.lingo
 */
public class FrmRemoteControl extends javax.swing.JFrame {
    
    RemoteControl rc = new RemoteControl();

    /**
     * Creates new form FrmRemoteControl
     */
    public FrmRemoteControl() {
        Command cmd;
        
        initComponents();

        //combine Command-objects and RemoteControl-slots
         //1.Slot
        txtCmdCaption1.setText("Wohnzimmer-Licht");
        Light light = new Light("Wohnzimmer-Licht");
        cmd = new LightOn(light);
        rc.insertOnCommand(0, cmd); 

        cmd = new LightOff(light);
        rc.insertOffCommand(0, cmd);
        
        // Sample für mehr Dynamik
        /*
        try {
            Light receiver = (Light) Class.forName("blogic.Light").getConstructor(String.class).newInstance("Wohnzimmer-Licht");
            cmd = (Command) Class.forName("blogic.LightOff").getConstructor(Light.class).newInstance(receiver);
        } catch (Exception ex) {
            Logger.getLogger(FrmRemoteControl.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
   


        //2.Slot
        txtCmdCaption2.setText("TV-Küche"); 
        cmd = new TvOn(new TV("TV-Küche"));
        rc.insertOnCommand(1, cmd);

        cmd = new TvOff(new TV("TV-Küche"));
        rc.insertOffCommand(1, cmd);  
        
        //3.Slot
         txtCmdCaption3.setText("Stereo Wohnzimmer"); 
        cmd = new StereoOn(new Stereo("Stereo Wohnzimmer"));
        rc.insertOnCommand(2, cmd);

        cmd = new StereoOff(new Stereo("Stereo Wohnzimmer"));
        rc.insertOffCommand(2, cmd);  
        
        //4.Slot
         txtCmdCaption4.setText("Hottub"); 
        cmd = new HottubOn(new Hottub());
        rc.insertOnCommand(3, cmd);

        cmd = new HottubOff(new Hottub());
        rc.insertOffCommand(3, cmd);
        
        //5.Slot
        txtCmdCaption5.setText("Macro-On"); 
        MacroCommand macro = new MacroCommand();
        macro.addCommand(new LightOn(new Light("Wohnzimmer-Licht")));
        macro.addCommand(new LightOn(new Light("Arbeitszimmer Licht")));
        macro.addCommand(new StereoOn(new Stereo("Stereo Wohnzimmer")));
        rc.insertOnCommand(4, macro);
        
        macro = new MacroCommand();
        macro.addCommand(new LightOff(new Light("Wohnzimmer-Licht")));
        macro.addCommand(new LightOff(new Light("Arbeitszimmer Licht")));
        macro.addCommand(new StereoOff(new Stereo("Stereo Wohnzimmer")));
        rc.insertOffCommand(4, macro);

  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCmdOn1 = new javax.swing.JButton();
        txtCmdOn4 = new javax.swing.JButton();
        txtCmdOn2 = new javax.swing.JButton();
        txtCmdOn3 = new javax.swing.JButton();
        txtCmdOn5 = new javax.swing.JButton();
        txtCmdCaption2 = new javax.swing.JTextField();
        txtCmdCaption1 = new javax.swing.JTextField();
        txtCmdCaption3 = new javax.swing.JTextField();
        txtCmdCaption4 = new javax.swing.JTextField();
        txtCmdCaption5 = new javax.swing.JTextField();
        txtCmdOff1 = new javax.swing.JButton();
        txtCmdOff2 = new javax.swing.JButton();
        txtCmdOff3 = new javax.swing.JButton();
        txtCmdOff4 = new javax.swing.JButton();
        txtCmdOff5 = new javax.swing.JButton();
        txtCmdUndo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCommandState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        txtCmdOn1.setText("ON");
        txtCmdOn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOn1ActionPerformed(evt);
            }
        });

        txtCmdOn4.setText("ON");
        txtCmdOn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOn4ActionPerformed(evt);
            }
        });

        txtCmdOn2.setText("ON");
        txtCmdOn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOn2ActionPerformed(evt);
            }
        });

        txtCmdOn3.setText("ON");
        txtCmdOn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOn3ActionPerformed(evt);
            }
        });

        txtCmdOn5.setText("ON");
        txtCmdOn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOn5ActionPerformed(evt);
            }
        });

        txtCmdOff1.setText("OFF");
        txtCmdOff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOff1ActionPerformed(evt);
            }
        });

        txtCmdOff2.setText("OFF");
        txtCmdOff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOff2ActionPerformed(evt);
            }
        });

        txtCmdOff3.setText("OFF");
        txtCmdOff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOff3ActionPerformed(evt);
            }
        });

        txtCmdOff4.setText("OFF");
        txtCmdOff4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOff4ActionPerformed(evt);
            }
        });

        txtCmdOff5.setText("OFF");
        txtCmdOff5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdOff5ActionPerformed(evt);
            }
        });

        txtCmdUndo.setText("UNDO");
        txtCmdUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmdUndoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Programable Control-Remote");

        lblCommandState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCommandState.setForeground(new java.awt.Color(255, 255, 255));
        lblCommandState.setText("Command");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCommandState, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmdCaption2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmdCaption1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmdCaption3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmdCaption4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmdCaption5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCmdOn5)
                            .addComponent(txtCmdOn3)
                            .addComponent(txtCmdOn2)
                            .addComponent(txtCmdOn4)
                            .addComponent(txtCmdOn1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCmdOff5)
                            .addComponent(txtCmdOff3)
                            .addComponent(txtCmdOff2)
                            .addComponent(txtCmdOff4)
                            .addComponent(txtCmdOff1)))
                    .addComponent(txtCmdUndo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblCommandState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCmdOff1)
                        .addGap(17, 17, 17)
                        .addComponent(txtCmdOff2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCmdOff3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCmdOff4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCmdOff5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCmdOn1)
                            .addComponent(txtCmdCaption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCmdOn2)
                            .addComponent(txtCmdCaption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCmdOn3)
                            .addComponent(txtCmdCaption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCmdOn4)
                            .addComponent(txtCmdCaption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCmdOn5)
                            .addComponent(txtCmdCaption5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(txtCmdUndo)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCmdOn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOn1ActionPerformed
        
        int index = 0;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOnCommand(index);
        }
    }//GEN-LAST:event_txtCmdOn1ActionPerformed

    private void txtCmdOn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOn4ActionPerformed
        
        int index = 3;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOnCommand(index);
        }
    }//GEN-LAST:event_txtCmdOn4ActionPerformed

    private void txtCmdOn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOn2ActionPerformed
        
        int index = 1;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOnCommand(index);
        }
    }//GEN-LAST:event_txtCmdOn2ActionPerformed

    private void txtCmdOn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOn3ActionPerformed
        int index = 2;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOnCommand(index);
        }
    }//GEN-LAST:event_txtCmdOn3ActionPerformed

    private void txtCmdOn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOn5ActionPerformed
        
        int index = 4;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOnCommand(index);
        }
    }//GEN-LAST:event_txtCmdOn5ActionPerformed

    private void txtCmdOff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOff1ActionPerformed
        
        int index = 0;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOffCommand(index);
        }
    }//GEN-LAST:event_txtCmdOff1ActionPerformed

    private void txtCmdOff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOff2ActionPerformed
        
        int index = 1;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOffCommand(index);
        }
    }//GEN-LAST:event_txtCmdOff2ActionPerformed

    private void txtCmdOff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOff3ActionPerformed
        
        int index = 2;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOffCommand(index);
        }
    }//GEN-LAST:event_txtCmdOff3ActionPerformed

    private void txtCmdOff4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOff4ActionPerformed
        
        int index = 3;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOffCommand(index);
        }
    }//GEN-LAST:event_txtCmdOff4ActionPerformed

    private void txtCmdOff5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdOff5ActionPerformed
        
        int index = 4;
        
        if (rc.getCommandsCount() >= index+1) 
        {
            rc.pressOffCommand(index);
        }
    }//GEN-LAST:event_txtCmdOff5ActionPerformed

    private void txtCmdUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmdUndoActionPerformed
        rc.undoLastCommand();
    }//GEN-LAST:event_txtCmdUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRemoteControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRemoteControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRemoteControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRemoteControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRemoteControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCommandState;
    private javax.swing.JTextField txtCmdCaption1;
    private javax.swing.JTextField txtCmdCaption2;
    private javax.swing.JTextField txtCmdCaption3;
    private javax.swing.JTextField txtCmdCaption4;
    private javax.swing.JTextField txtCmdCaption5;
    private javax.swing.JButton txtCmdOff1;
    private javax.swing.JButton txtCmdOff2;
    private javax.swing.JButton txtCmdOff3;
    private javax.swing.JButton txtCmdOff4;
    private javax.swing.JButton txtCmdOff5;
    private javax.swing.JButton txtCmdOn1;
    private javax.swing.JButton txtCmdOn2;
    private javax.swing.JButton txtCmdOn3;
    private javax.swing.JButton txtCmdOn4;
    private javax.swing.JButton txtCmdOn5;
    private javax.swing.JButton txtCmdUndo;
    // End of variables declaration//GEN-END:variables
}
